# Generated by Django 3.0.2 on 2020-01-27 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Registraion',
            new_name='TicketRegistraion',
        ),
        migrations.AlterField(
            model_name='customer',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customer',
            name='title',
            field=models.CharField(choices=[('Dr.', 'Dr'), ('Mr.', 'Mr'), ('Mrs.', 'Mrs'), ('Ms.', 'Ms')], max_length=4),
        ),
    ]
