# Generated by Django 3.0.2 on 2020-01-29 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='age_restriction',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='length',
        ),
    ]
