# Generated by Django 3.0.2 on 2020-01-30 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0002_auto_20200130_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='cinema_movie',
            name='fk_cinema',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='cinema.Cinema'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cinema_movie',
            name='fk_movie',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='cinema.Movie'),
            preserve_default=False,
        ),
    ]
