# Generated by Django 3.0.2 on 2020-01-29 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0002_auto_20200129_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='age_restriction',
            field=models.IntegerField(default=18, max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='length',
            field=models.IntegerField(default=0, max_length=4),
            preserve_default=False,
        ),
    ]
