# Generated by Django 3.0.2 on 2020-01-29 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0003_auto_20200129_1131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='age_restriction',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='length',
        ),
    ]
