# Generated by Django 3.0.2 on 2020-01-29 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0004_auto_20200129_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='age_restriction',
            field=models.IntegerField(default=18),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='length',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
